# Generated by Django 4.2.7 on 2023-11-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookreview',
            old_name='start_give',
            new_name='stars_give',
        ),
    ]
